theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  logo:
    header: "/assets/images/logo_blanc.svg"
    header: "/assets/images/logo.svg"
  posts:
    index:
      show_categories: true